#############################################################################
# Makefile for building: client1
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  LTM-MeetingScheduler.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile LTM-MeetingScheduler.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Isrc -Isrc/views -Isrc/controllers -Isrc/utils -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = client11.0.0
DISTDIR = /home/dinhnam/Desktop/LTM-MeetingScheduler/.tmp/client11.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lmysqlcppconn /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/client/Client1.cpp \
		src/views/teacherviews/timeslotdialog.cpp \
		src/views/teacherviews/viewtimeslotsdialog.cpp \
		src/views/teacherviews/update_timeslot_dialog.cpp \
		src/views/teacherviews/teacherviewmeetingsdialog.cpp \
		src/views/teacherviews/meetingdetaildialog.cpp \
		src/views/teacherviews/meetingcalendarwidget.cpp \
		src/views/teacherviews/meetinghistorydialog.cpp \
		src/views/teacherviews/viewmeetinghistorydialog.cpp \
		src/views/teacherviews/viewweeklymeetingsdialog.cpp \
		src/views/userviews/loginwidget.cpp \
		src/views/userviews/mainmenu.cpp \
		src/views/userviews/registerwidget.cpp moc_timeslotdialog.cpp \
		moc_viewtimeslotsdialog.cpp \
		moc_update_timeslot_dialog.cpp \
		moc_teacherviewmeetingsdialog.cpp \
		moc_meetingdetaildialog.cpp \
		moc_meetingcalendarwidget.cpp \
		moc_meetinghistorydialog.cpp \
		moc_viewmeetinghistorydialog.cpp \
		moc_viewweeklymeetingsdialog.cpp \
		moc_loginwidget.cpp \
		moc_mainmenu.cpp \
		moc_registerwidget.cpp
OBJECTS       = Client1.o \
		timeslotdialog.o \
		viewtimeslotsdialog.o \
		update_timeslot_dialog.o \
		teacherviewmeetingsdialog.o \
		meetingdetaildialog.o \
		meetingcalendarwidget.o \
		meetinghistorydialog.o \
		viewmeetinghistorydialog.o \
		viewweeklymeetingsdialog.o \
		loginwidget.o \
		mainmenu.o \
		registerwidget.o \
		moc_timeslotdialog.o \
		moc_viewtimeslotsdialog.o \
		moc_update_timeslot_dialog.o \
		moc_teacherviewmeetingsdialog.o \
		moc_meetingdetaildialog.o \
		moc_meetingcalendarwidget.o \
		moc_meetinghistorydialog.o \
		moc_viewmeetinghistorydialog.o \
		moc_viewweeklymeetingsdialog.o \
		moc_loginwidget.o \
		moc_mainmenu.o \
		moc_registerwidget.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		LTM-MeetingScheduler.pro src/views/teacherviews/timeslotdialog.h \
		src/views/teacherviews/viewtimeslotsdialog.h \
		src/views/teacherviews/update_timeslot_dialog.h \
		src/views/teacherviews/teacherviewmeetingsdialog.h \
		src/views/teacherviews/meetingdetaildialog.h \
		src/views/teacherviews/meetingcalendarwidget.h \
		src/views/teacherviews/meetinghistorydialog.h \
		src/views/teacherviews/viewmeetinghistorydialog.h \
		src/views/teacherviews/viewweeklymeetingsdialog.h \
		src/views/userviews/loginwidget.h \
		src/views/userviews/mainmenu.h \
		src/views/userviews/registerwidget.h src/client/Client1.cpp \
		src/views/teacherviews/timeslotdialog.cpp \
		src/views/teacherviews/viewtimeslotsdialog.cpp \
		src/views/teacherviews/update_timeslot_dialog.cpp \
		src/views/teacherviews/teacherviewmeetingsdialog.cpp \
		src/views/teacherviews/meetingdetaildialog.cpp \
		src/views/teacherviews/meetingcalendarwidget.cpp \
		src/views/teacherviews/meetinghistorydialog.cpp \
		src/views/teacherviews/viewmeetinghistorydialog.cpp \
		src/views/teacherviews/viewweeklymeetingsdialog.cpp \
		src/views/userviews/loginwidget.cpp \
		src/views/userviews/mainmenu.cpp \
		src/views/userviews/registerwidget.cpp
QMAKE_TARGET  = client1
DESTDIR       = 
TARGET        = client1


first: all
####### Build rules

client1: ui_timeslotdialog.h ui_viewtimeslotsdialog.h ui_update_timeslot_dialog.h ui_teacherviewmeetingsdialog.h ui_meetingdetaildialog.h ui_meetinghistorydialog.h ui_viewmeetinghistorydialog.h ui_viewweeklymeetingsdialog.h ui_loginwidget.h ui_mainmenu.h ui_registerwidget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: LTM-MeetingScheduler.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		LTM-MeetingScheduler.pro
	$(QMAKE) -o Makefile LTM-MeetingScheduler.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
LTM-MeetingScheduler.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile LTM-MeetingScheduler.pro

qmake_all: FORCE


all: Makefile client1

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/views/teacherviews/timeslotdialog.h src/views/teacherviews/viewtimeslotsdialog.h src/views/teacherviews/update_timeslot_dialog.h src/views/teacherviews/teacherviewmeetingsdialog.h src/views/teacherviews/meetingdetaildialog.h src/views/teacherviews/meetingcalendarwidget.h src/views/teacherviews/meetinghistorydialog.h src/views/teacherviews/viewmeetinghistorydialog.h src/views/teacherviews/viewweeklymeetingsdialog.h src/views/userviews/loginwidget.h src/views/userviews/mainmenu.h src/views/userviews/registerwidget.h $(DISTDIR)/
	$(COPY_FILE) --parents src/client/Client1.cpp src/views/teacherviews/timeslotdialog.cpp src/views/teacherviews/viewtimeslotsdialog.cpp src/views/teacherviews/update_timeslot_dialog.cpp src/views/teacherviews/teacherviewmeetingsdialog.cpp src/views/teacherviews/meetingdetaildialog.cpp src/views/teacherviews/meetingcalendarwidget.cpp src/views/teacherviews/meetinghistorydialog.cpp src/views/teacherviews/viewmeetinghistorydialog.cpp src/views/teacherviews/viewweeklymeetingsdialog.cpp src/views/userviews/loginwidget.cpp src/views/userviews/mainmenu.cpp src/views/userviews/registerwidget.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/views/teacherviews/timeslotdialog.ui src/views/teacherviews/viewtimeslotsdialog.ui src/views/teacherviews/update_timeslot_dialog.ui src/views/teacherviews/teacherviewmeetingsdialog.ui src/views/teacherviews/meetingdetaildialog.ui src/views/teacherviews/meetinghistorydialog.ui src/views/teacherviews/viewmeetinghistorydialog.ui src/views/teacherviews/viewweeklymeetingsdialog.ui src/views/userviews/loginwidget.ui src/views/userviews/mainmenu.ui src/views/userviews/registerwidget.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_timeslotdialog.cpp moc_viewtimeslotsdialog.cpp moc_update_timeslot_dialog.cpp moc_teacherviewmeetingsdialog.cpp moc_meetingdetaildialog.cpp moc_meetingcalendarwidget.cpp moc_meetinghistorydialog.cpp moc_viewmeetinghistorydialog.cpp moc_viewweeklymeetingsdialog.cpp moc_loginwidget.cpp moc_mainmenu.cpp moc_registerwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_timeslotdialog.cpp moc_viewtimeslotsdialog.cpp moc_update_timeslot_dialog.cpp moc_teacherviewmeetingsdialog.cpp moc_meetingdetaildialog.cpp moc_meetingcalendarwidget.cpp moc_meetinghistorydialog.cpp moc_viewmeetinghistorydialog.cpp moc_viewweeklymeetingsdialog.cpp moc_loginwidget.cpp moc_mainmenu.cpp moc_registerwidget.cpp
moc_timeslotdialog.cpp: src/views/teacherviews/timeslotdialog.h \
		src/models/Timeslot.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dinhnam/Desktop/LTM-MeetingScheduler/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dinhnam/Desktop/LTM-MeetingScheduler -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/views -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/controllers -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/teacherviews/timeslotdialog.h -o moc_timeslotdialog.cpp

moc_viewtimeslotsdialog.cpp: src/views/teacherviews/viewtimeslotsdialog.h \
		src/models/Timeslot.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dinhnam/Desktop/LTM-MeetingScheduler/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dinhnam/Desktop/LTM-MeetingScheduler -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/views -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/controllers -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/teacherviews/viewtimeslotsdialog.h -o moc_viewtimeslotsdialog.cpp

moc_update_timeslot_dialog.cpp: src/views/teacherviews/update_timeslot_dialog.h \
		src/models/Timeslot.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dinhnam/Desktop/LTM-MeetingScheduler/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dinhnam/Desktop/LTM-MeetingScheduler -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/views -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/controllers -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/teacherviews/update_timeslot_dialog.h -o moc_update_timeslot_dialog.cpp

moc_teacherviewmeetingsdialog.cpp: src/views/teacherviews/teacherviewmeetingsdialog.h \
		src/models/Meeting.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dinhnam/Desktop/LTM-MeetingScheduler/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dinhnam/Desktop/LTM-MeetingScheduler -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/views -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/controllers -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/teacherviews/teacherviewmeetingsdialog.h -o moc_teacherviewmeetingsdialog.cpp

moc_meetingdetaildialog.cpp: src/views/teacherviews/meetingdetaildialog.h \
		src/models/Meeting.h \
		src/models/User.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dinhnam/Desktop/LTM-MeetingScheduler/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dinhnam/Desktop/LTM-MeetingScheduler -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/views -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/controllers -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/teacherviews/meetingdetaildialog.h -o moc_meetingdetaildialog.cpp

moc_meetingcalendarwidget.cpp: src/views/teacherviews/meetingcalendarwidget.h \
		src/models/Meeting.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dinhnam/Desktop/LTM-MeetingScheduler/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dinhnam/Desktop/LTM-MeetingScheduler -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/views -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/controllers -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/teacherviews/meetingcalendarwidget.h -o moc_meetingcalendarwidget.cpp

moc_meetinghistorydialog.cpp: src/views/teacherviews/meetinghistorydialog.h \
		src/models/Meeting.h \
		src/models/User.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dinhnam/Desktop/LTM-MeetingScheduler/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dinhnam/Desktop/LTM-MeetingScheduler -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/views -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/controllers -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/teacherviews/meetinghistorydialog.h -o moc_meetinghistorydialog.cpp

moc_viewmeetinghistorydialog.cpp: src/views/teacherviews/viewmeetinghistorydialog.h \
		src/models/Meeting.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dinhnam/Desktop/LTM-MeetingScheduler/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dinhnam/Desktop/LTM-MeetingScheduler -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/views -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/controllers -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/teacherviews/viewmeetinghistorydialog.h -o moc_viewmeetinghistorydialog.cpp

moc_viewweeklymeetingsdialog.cpp: src/views/teacherviews/viewweeklymeetingsdialog.h \
		src/models/Meeting.h \
		src/models/User.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dinhnam/Desktop/LTM-MeetingScheduler/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dinhnam/Desktop/LTM-MeetingScheduler -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/views -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/controllers -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/teacherviews/viewweeklymeetingsdialog.h -o moc_viewweeklymeetingsdialog.cpp

moc_loginwidget.cpp: src/views/userviews/loginwidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dinhnam/Desktop/LTM-MeetingScheduler/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dinhnam/Desktop/LTM-MeetingScheduler -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/views -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/controllers -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/userviews/loginwidget.h -o moc_loginwidget.cpp

moc_mainmenu.cpp: src/views/userviews/mainmenu.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dinhnam/Desktop/LTM-MeetingScheduler/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dinhnam/Desktop/LTM-MeetingScheduler -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/views -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/controllers -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/userviews/mainmenu.h -o moc_mainmenu.cpp

moc_registerwidget.cpp: src/views/userviews/registerwidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dinhnam/Desktop/LTM-MeetingScheduler/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dinhnam/Desktop/LTM-MeetingScheduler -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/views -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/controllers -I/home/dinhnam/Desktop/LTM-MeetingScheduler/src/utils -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/userviews/registerwidget.h -o moc_registerwidget.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_timeslotdialog.h ui_viewtimeslotsdialog.h ui_update_timeslot_dialog.h ui_teacherviewmeetingsdialog.h ui_meetingdetaildialog.h ui_meetinghistorydialog.h ui_viewmeetinghistorydialog.h ui_viewweeklymeetingsdialog.h ui_loginwidget.h ui_mainmenu.h ui_registerwidget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_timeslotdialog.h ui_viewtimeslotsdialog.h ui_update_timeslot_dialog.h ui_teacherviewmeetingsdialog.h ui_meetingdetaildialog.h ui_meetinghistorydialog.h ui_viewmeetinghistorydialog.h ui_viewweeklymeetingsdialog.h ui_loginwidget.h ui_mainmenu.h ui_registerwidget.h
ui_timeslotdialog.h: src/views/teacherviews/timeslotdialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/teacherviews/timeslotdialog.ui -o ui_timeslotdialog.h

ui_viewtimeslotsdialog.h: src/views/teacherviews/viewtimeslotsdialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/teacherviews/viewtimeslotsdialog.ui -o ui_viewtimeslotsdialog.h

ui_update_timeslot_dialog.h: src/views/teacherviews/update_timeslot_dialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/teacherviews/update_timeslot_dialog.ui -o ui_update_timeslot_dialog.h

ui_teacherviewmeetingsdialog.h: src/views/teacherviews/teacherviewmeetingsdialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/teacherviews/teacherviewmeetingsdialog.ui -o ui_teacherviewmeetingsdialog.h

ui_meetingdetaildialog.h: src/views/teacherviews/meetingdetaildialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/teacherviews/meetingdetaildialog.ui -o ui_meetingdetaildialog.h

ui_meetinghistorydialog.h: src/views/teacherviews/meetinghistorydialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/teacherviews/meetinghistorydialog.ui -o ui_meetinghistorydialog.h

ui_viewmeetinghistorydialog.h: src/views/teacherviews/viewmeetinghistorydialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/teacherviews/viewmeetinghistorydialog.ui -o ui_viewmeetinghistorydialog.h

ui_viewweeklymeetingsdialog.h: src/views/teacherviews/viewweeklymeetingsdialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/teacherviews/viewweeklymeetingsdialog.ui -o ui_viewweeklymeetingsdialog.h

ui_loginwidget.h: src/views/userviews/loginwidget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/userviews/loginwidget.ui -o ui_loginwidget.h

ui_mainmenu.h: src/views/userviews/mainmenu.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/userviews/mainmenu.ui -o ui_mainmenu.h

ui_registerwidget.h: src/views/userviews/registerwidget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/userviews/registerwidget.ui -o ui_registerwidget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

Client1.o: src/client/Client1.cpp src/controllers/ClientController.h \
		src/models/Response.h \
		src/models/User.h \
		src/repository/TimeslotRepository.h \
		data/Database.h \
		environment.h \
		src/models/Timeslot.h \
		src/utils/Utils.h \
		src/repository/UserRepository.h \
		src/controllers/StudentController.h \
		src/models/Meeting.h \
		src/repository/MeetingRepository.h \
		src/models/Attendance.h \
		src/repository/AttendanceRepository.h \
		src/controllers/TeacherController.h \
		src/controllers/ResponseController.h \
		src/controllers/UserController.h \
		src/utils/MessageUtils.h \
		src/Status.h \
		src/views/StudentView.h \
		src/views/TeacherView.h \
		src/views/UserView.h \
		src/views/teacherviews/timeslotdialog.h \
		src/views/teacherviews/viewtimeslotsdialog.h \
		src/views/teacherviews/update_timeslot_dialog.h \
		src/views/teacherviews/teacherviewmeetingsdialog.h \
		src/views/teacherviews/meetingdetaildialog.h \
		src/views/teacherviews/meetinghistorydialog.h \
		src/views/teacherviews/viewmeetinghistorydialog.h \
		src/views/teacherviews/viewweeklymeetingsdialog.h \
		src/views/userviews/loginwidget.h \
		src/views/userviews/mainmenu.h \
		src/views/userviews/registerwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Client1.o src/client/Client1.cpp

timeslotdialog.o: src/views/teacherviews/timeslotdialog.cpp src/views/teacherviews/timeslotdialog.h \
		src/models/Timeslot.h \
		ui_timeslotdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timeslotdialog.o src/views/teacherviews/timeslotdialog.cpp

viewtimeslotsdialog.o: src/views/teacherviews/viewtimeslotsdialog.cpp src/views/teacherviews/viewtimeslotsdialog.h \
		src/models/Timeslot.h \
		ui_viewtimeslotsdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewtimeslotsdialog.o src/views/teacherviews/viewtimeslotsdialog.cpp

update_timeslot_dialog.o: src/views/teacherviews/update_timeslot_dialog.cpp src/views/teacherviews/update_timeslot_dialog.h \
		src/models/Timeslot.h \
		ui_update_timeslot_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o update_timeslot_dialog.o src/views/teacherviews/update_timeslot_dialog.cpp

teacherviewmeetingsdialog.o: src/views/teacherviews/teacherviewmeetingsdialog.cpp src/views/teacherviews/teacherviewmeetingsdialog.h \
		src/models/Meeting.h \
		ui_teacherviewmeetingsdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o teacherviewmeetingsdialog.o src/views/teacherviews/teacherviewmeetingsdialog.cpp

meetingdetaildialog.o: src/views/teacherviews/meetingdetaildialog.cpp src/views/teacherviews/meetingdetaildialog.h \
		src/models/Meeting.h \
		src/models/User.h \
		ui_meetingdetaildialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o meetingdetaildialog.o src/views/teacherviews/meetingdetaildialog.cpp

meetingcalendarwidget.o: src/views/teacherviews/meetingcalendarwidget.cpp src/views/teacherviews/meetingcalendarwidget.h \
		src/models/Meeting.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o meetingcalendarwidget.o src/views/teacherviews/meetingcalendarwidget.cpp

meetinghistorydialog.o: src/views/teacherviews/meetinghistorydialog.cpp src/views/teacherviews/meetinghistorydialog.h \
		src/models/Meeting.h \
		src/models/User.h \
		ui_meetinghistorydialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o meetinghistorydialog.o src/views/teacherviews/meetinghistorydialog.cpp

viewmeetinghistorydialog.o: src/views/teacherviews/viewmeetinghistorydialog.cpp src/views/teacherviews/viewmeetinghistorydialog.h \
		src/models/Meeting.h \
		ui_viewmeetinghistorydialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewmeetinghistorydialog.o src/views/teacherviews/viewmeetinghistorydialog.cpp

viewweeklymeetingsdialog.o: src/views/teacherviews/viewweeklymeetingsdialog.cpp src/views/teacherviews/viewweeklymeetingsdialog.h \
		src/models/Meeting.h \
		src/models/User.h \
		ui_viewweeklymeetingsdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewweeklymeetingsdialog.o src/views/teacherviews/viewweeklymeetingsdialog.cpp

loginwidget.o: src/views/userviews/loginwidget.cpp src/views/userviews/loginwidget.h \
		ui_loginwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loginwidget.o src/views/userviews/loginwidget.cpp

mainmenu.o: src/views/userviews/mainmenu.cpp src/views/userviews/mainmenu.h \
		ui_mainmenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainmenu.o src/views/userviews/mainmenu.cpp

registerwidget.o: src/views/userviews/registerwidget.cpp src/views/userviews/registerwidget.h \
		ui_registerwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o registerwidget.o src/views/userviews/registerwidget.cpp

moc_timeslotdialog.o: moc_timeslotdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_timeslotdialog.o moc_timeslotdialog.cpp

moc_viewtimeslotsdialog.o: moc_viewtimeslotsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_viewtimeslotsdialog.o moc_viewtimeslotsdialog.cpp

moc_update_timeslot_dialog.o: moc_update_timeslot_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_update_timeslot_dialog.o moc_update_timeslot_dialog.cpp

moc_teacherviewmeetingsdialog.o: moc_teacherviewmeetingsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_teacherviewmeetingsdialog.o moc_teacherviewmeetingsdialog.cpp

moc_meetingdetaildialog.o: moc_meetingdetaildialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_meetingdetaildialog.o moc_meetingdetaildialog.cpp

moc_meetingcalendarwidget.o: moc_meetingcalendarwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_meetingcalendarwidget.o moc_meetingcalendarwidget.cpp

moc_meetinghistorydialog.o: moc_meetinghistorydialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_meetinghistorydialog.o moc_meetinghistorydialog.cpp

moc_viewmeetinghistorydialog.o: moc_viewmeetinghistorydialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_viewmeetinghistorydialog.o moc_viewmeetinghistorydialog.cpp

moc_viewweeklymeetingsdialog.o: moc_viewweeklymeetingsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_viewweeklymeetingsdialog.o moc_viewweeklymeetingsdialog.cpp

moc_loginwidget.o: moc_loginwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loginwidget.o moc_loginwidget.cpp

moc_mainmenu.o: moc_mainmenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainmenu.o moc_mainmenu.cpp

moc_registerwidget.o: moc_registerwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_registerwidget.o moc_registerwidget.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

